# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonOne = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOne.setGeometry(QtCore.QRect(240, 600, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.buttonOne.setFont(font)
        self.buttonOne.setStyleSheet("background-color: rgb(255, 85, 255);")
        self.buttonOne.setObjectName("buttonOne")
        self.buttonTwo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTwo.setGeometry(QtCore.QRect(400, 600, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.buttonTwo.setFont(font)
        self.buttonTwo.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.buttonTwo.setObjectName("buttonTwo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 350, 47, 13))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonOne.setText(_translate("MainWindow", "Button One"))
        self.buttonTwo.setText(_translate("MainWindow", "Button Two"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
